#:schema https://developers.openai.com/codex/config-schema.json

approval_policy = "on-request"
model_provider = "oca"
model = "oca/gpt-5.3-codex" # needed for VS Code because it ignores profile
profile = "gpt-5-3-codex"
sandbox_mode = "workspace-write"
web_search = "live"

[projects."/Users/"]
trust_level = "trusted"

[model_providers.oca]
base_url = "https://code-internal.aiservice.us-chicago-1.oci.oraclecloud.com/20250206/app/litellm"
http_headers = { "client" = "codex-cli", "client-version" = "0" }
model = "oca/gpt5"
name = "Oracle Code Assist"
wire_api = "responses"

[profiles.gpt-4-1]
model = "oca/gpt-4.1"
model_provider = "oca"
review_model = "oca/gpt-4.1"

[profiles.gpt-5]
model = "oca/gpt5"
model_provider = "oca"
review_model = "oca/gpt5"

[profiles.gpt-5-2]
model = "oca/gpt-5.2"
model_provider = "oca"
review_model = "oca/gpt-5.2"

[profiles.gpt-5-codex]
model = "oca/gpt-5-codex"
model_provider = "oca"
review_model = "oca/gpt-5-codex"
personality = "pragmatic"

[profiles.gpt-5-1-codex]
model = "oca/gpt-5.1-codex"
model_provider = "oca"
review_model = "oca/gpt-5.1-codex"
personality = "pragmatic"

[profiles.gpt-5-1-codex-mini]
model = "oca/gpt-5.1-codex-mini"
model_provider = "oca"
review_model = "oca/gpt-5.1-codex-mini"
personality = "pragmatic"

[profiles.gpt-5-1-codex-max]
model = "oca/gpt-5.1-codex-max"
model_provider = "oca"
review_model = "oca/gpt-5.1-codex-max"
personality = "pragmatic"

[profiles.gpt-5-2-codex]
model = "oca/gpt-5.2-codex"
model_provider = "oca"
review_model = "oca/gpt-5.2-codex"
personality = "pragmatic"

[profiles.gpt-5-3-codex]
model = "oca/gpt-5.3-codex"
model_provider = "oca"
review_model = "oca/gpt-5.3-codex"
personality = "pragmatic"
